---
- name: Fetch localization facts
  shell: localectl status | grep "VC Keymap" | grep -q "{{ locale_keymap }}"
  ignore_errors: yes
  register: wtd_keymap_status
  changed_when: wtd_keymap_status.rc != 0
  failed_when: wtd_keymap_status.rc != 1 and wtd_keymap_status.rc != 0
  tags:
    - localization
    - locale

- name: Set localization
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - localization
    - locale

- name: Set keymap
  command: localectl set-keymap "{{ locale_keymap }}"
  when: keymap_status.rc == 1
  tags:
    - localization
    - keyboard
